// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using PremiumGateWay_svc.Models;
using System;

#nullable disable

namespace PremiumGateWay_svc.Data
{
    public partial class AppDBContext : DbContext
    {
        public AppDBContext()
        {
        }
    }
}